### ISSUE TITLE
use MOOSE optimization module

### ISSUE THREAD

**Issue by lynnmunday** [idaholab/isopod#60]
Delete all of the code that was moved to the MOOSE optimization module and start using the optimization module.  Delete duplicated documentation.

**Comment by GiudGiud** [comment]
For the latest failure involving the FullSolveOptimizationmultiapp, arising from https://github.com/idaholab/moose/pull/22583

- the object is likely to get deleted anyway because it's not used in the optimization module, it s no longer necessary
- the change is trivial. We went from a boolean to keep track of resets to a vector to keep track of multiple resets. The optimization process would likely only use the first element of that vector.
